# example GitHub workflow

name: Publish resume in JSONResume format as PDF
 
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish_resume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      - name: Install the dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y git
          npm install resume-cli
          git clone https://github.com/ghandic/jsonresume-theme-stackoverflow.git
          cd jsonresume-theme-stackoverflow
          npm install .
          cd ..
          ls
          cd node_modules
          ls
          cd..
          mkdir public

      - name: Build the resume - pdf
        run: |
          cd node_modules
          cd resume-cli
          cd build
          ls
          cd ..
          cd ..
          cd ..
          script --return --quiet -c "node_modules/resume-cli export _data/cv.json --theme stackoverflow --format pdf Owen_Burroughs_Resume.pdf" /dev/null
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Owen_Burroughs_Resume.pdf
          git commit -m "Publishing latest PDF"

      - name: Deploy the resume - pdf
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
